# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' BQR Based on ALD
#'
#' Bayesian quantile regression using the Asymetric Laplacian Distribution (ALD) as Likelihood Function.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param sigma The prespecified scale parameter of the asymmetric Laplace distribution.
#' @param burn Number of burn-in.
#' @return List of model coefficients and acceptance rate.
#' @export
#'
bqrALD <- function(Xr, Yr, p, nsim, initCoef, sigma, burn = 5000L) {
    .Call('_bqrDPM_bqrALD', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, sigma, burn)
}

#' BQR Based on DE
#'
#'Bayesian quantile regression using double exponential distribution (DE) as Likelihood Function.
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param burn Number of burn-in.
#' @return List of model coefficients and acceptance rate.
#' @export
#'
bqrDE <- function(Xr, Yr, p, nsim, initCoef, burn = 5000L) {
    .Call('_bqrDPM_bqrDE', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, burn)
}

#' BQR Based on DPM of Logistic Distribution
#'
#' Bayesian quantile regression with Dirichlet process mixture of Logistic Distribution.
#' It is the main and recommended method of this package.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param sampleQ A boolean variable which determines how to calculate the location shift.
#'   (true means using sample quantile, false means using the density estimation)
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param naux Number of the auxiliary variable.
#' @param threshold The threshold of the error of the solution to the equation of the lambda.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPML <- function(Xr, Yr, p, nsim, initCoef, sampleQ = TRUE, burn = 5000L, plotDensity = FALSE, naux = 10L, threshold = 0.0000001) {
    .Call('_bqrDPM_bqrDPML', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, sampleQ, burn, plotDensity, naux, threshold)
}

#' BQR with Heteroskedasticity based on DPM of Logistic Distribution
#'
#' Bayesian quantile regression with heteroskedasticity term based on Dirichlet process mixture of Logistic Distribution.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param sampleQ A boolean variable which determines how to calculate the location shift.
#'   (true means using sample quantile, false means using the density estimation)
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param naux Number of the auxiliary variable.
#' @param threshold The threshold of the error of the solution to the equation of the lambda.
#' @param hasHeter Boolean indication whether heteroskedasticity is present in the model.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMLH <- function(Xr, Yr, p, nsim, initCoef, sampleQ = TRUE, burn = 5000L, plotDensity = FALSE, naux = 10L, threshold = 0.0000001, hasHeter = TRUE) {
    .Call('_bqrDPM_bqrDPMLH', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, sampleQ, burn, plotDensity, naux, threshold, hasHeter)
}

#' BQR with Heteroskedasticity based on DPM of Logistic Distribution (What does A mean?)
#'
#' Bayesian quantile regression with heteroskedasticity term based on Dirichlet process mixture of Logistic Distribution.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param sampleQ A boolean variable which determines how to calculate the location shift.
#'   (true means using sample quantile, false means using the density estimation)
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param naux Number of the auxiliary variable.
#' @param threshold The threshold of the error of the solution to the equation of the lambda.
#' @param hasHeter Boolean indication whether heteroskedasticity is present in the model.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMLHA <- function(Xr, Yr, p, nsim, initCoef, sampleQ = TRUE, burn = 5000L, plotDensity = FALSE, nF = 10L, threshold = 0.0000001, hasHeter = TRUE) {
    .Call('_bqrDPM_bqrDPMLHA', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, sampleQ, burn, plotDensity, nF, threshold, hasHeter)
}

#' BQR based on DPM of Mixure of Normal Distributions (what is 'A'?)
#'
#' Bayesian quantile regression based on Dirichlet process mixture of mixture of two normal distributions.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param tau Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param nF The number of terms in the finite approximation.
#' @param aD,bD V_k~Beta(1, D) and D~dgamma(aD, bD).
#' @param maxSigma The maximum possible value for sigma.
#' @param precBeta beta[j] ~ norm(0, 1/sqrt(prec.beta)).
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMMNA <- function(Xr, Yr, tau, nsim, initCoef, burn = 5000L, plotDensity = FALSE, nF = 10L, aD = 100, bD = 100, maxSigma = 1.0/0.0, precBeta = 0.000001) {
    .Call('_bqrDPM_bqrDPMMNA', PACKAGE = 'bqrDPM', Xr, Yr, tau, nsim, initCoef, burn, plotDensity, nF, aD, bD, maxSigma, precBeta)
}

#' BQR with Heteroskedasticity based on DPM of Mixure of Normal Distributions (what is 'A'?)
#'
#' Bayesian quantile regression with Heteroskedasticity based on Dirichlet process mixture of mixture of two normal distributions.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param tau Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param nF The number of terms in the finite approximation.
#' @param aD,bD V_k~Beta(1, D) and D~dgamma(aD, bD).
#' @param maxSigma The maximum possible value for sigma.
#' @param precBeta beta[j] ~ norm(0, 1/sqrt(prec.beta)).
#' @param hasHeter Boolean indicating if Heteroskedasticity is present. Default is True.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMMNHA <- function(Xr, Yr, tau, nsim, initCoef, burn = 5000L, plotDensity = FALSE, nF = 10L, aD = 100, bD = 100, maxSigma = 1.0/0.0, precBeta = 0.000001, hasHeter = TRUE) {
    .Call('_bqrDPM_bqrDPMMNHA', PACKAGE = 'bqrDPM', Xr, Yr, tau, nsim, initCoef, burn, plotDensity, nF, aD, bD, maxSigma, precBeta, hasHeter)
}

calcQNormalMixMN <- function(prob, sigma2Star, muStar, p, n) {
    .Call('_bqrDPM_calcQNormalMixMN', PACKAGE = 'bqrDPM', prob, sigma2Star, muStar, p, n)
}

#' BQR based on DPM of Normal Distribution
#'
#' Bayesian quantile regression with Dirichlet process mixture of normal distribution.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param sampleQ A boolean variable which determines how to calculate the location shift.
#'   (true means using sample quantile, false means using the density estimation)
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMN <- function(Xr, Yr, p, nsim, initCoef, sampleQ = TRUE, burn = 5000L, plotDensity = FALSE) {
    .Call('_bqrDPM_bqrDPMN', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, sampleQ, burn, plotDensity)
}

#' BQR based on DPM of Normal Distribution?
#'
#' Bayesian quantile regression with heteroskedasticity with Dirichlet process mixture of normal distribution.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param sampleQ A boolean variable which determines how to calculate the location shift.
#'   (true means using sample quantile, false means using the density estimation)
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param hasHeter Boolean indicating if Heteroskedasticity is present. Default is True.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMNH <- function(Xr, Yr, p, nsim, initCoef, sampleQ = TRUE, burn = 5000L, plotDensity = FALSE, hasHeter = TRUE) {
    .Call('_bqrDPM_bqrDPMNH', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, sampleQ, burn, plotDensity, hasHeter)
}

#' BQR based on DPM of Normal Distribution? (what is 'P'?)
#'
#' Bayesian quantile regression with heteroskedasticity with Dirichlet process mixture of normal distribution.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param sampleQ A boolean variable which determines how to calculate the location shift.
#'   (true means using sample quantile, false means using the density estimation)
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param hasHeter Boolean indicating if Heteroskedasticity is present. Default is True.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMNHP <- function(Xr, Yr, T, p, nsim, initCoef, burn = 5000L, plotDensity = FALSE, hasHeter = TRUE) {
    .Call('_bqrDPM_bqrDPMNHP', PACKAGE = 'bqrDPM', Xr, Yr, T, p, nsim, initCoef, burn, plotDensity, hasHeter)
}

#' BQR based on DPM of Uniform Distribution
#'
#' Bayesian quantile regression with Dirichlet process mixture of uniform distribution.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param tol The tolerance value for the length of the interval to treat the normal density in this interval as constant.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMU <- function(Xr, Yr, p, nsim, initCoef, burn = 5000L, plotDensity = FALSE, tol = 0.0000001) {
    .Call('_bqrDPM_bqrDPMU', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, burn, plotDensity, tol)
}

#' BQR with Heteroskedasticity based on DPM of Uniform Distribution
#'
#' Bayesian quantile regression with Heteroskedasticity based on Dirichlet process mixture of uniform distribution.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param burn Number of burn-in.
#' @param plotDensity A boolean variable which decides whether to plot the density estimation or not.
#' @param tol The tolerance value for the length of the interval to treat the normal density in this interval as constant.
#' @param hasHeter Boolean indicating if Heteroskedasticity is present. Default is True.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrDPMUH <- function(Xr, Yr, p, nsim, initCoef, burn = 5000L, plotDensity = FALSE, tol = 0.0000001, hasHeter = TRUE) {
    .Call('_bqrDPM_bqrDPMUH', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, burn, plotDensity, tol, hasHeter)
}

#' BQR Based on Normal Distribution
#'
#'Bayesian quantile regression using normal distribution as Likelihood Function.
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param burn Number of burn-in.
#' @return List of model coefficients and acceptance rate.
#' @export
#'
bqrN <- function(Xr, Yr, p, nsim, initCoef, burn = 5000L) {
    .Call('_bqrDPM_bqrN', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, burn)
}

#' BQR with Heteroscedasticity Based on Normal Distribution
#'
#'Bayesian quantile regression with heteroscedasticity using normal distribution as Likelihood Function.
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param burn Number of burn-in.
#' @return List of model coefficients and acceptance rate.
#' @export
#'
bqrNH <- function(Xr, Yr, p, nsim, initCoef, burn = 5000L) {
    .Call('_bqrDPM_bqrNH', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, burn)
}

#' BQR Based on Mixture of Normal Distribution
#'
#'Bayesian quantile regression using a mixture of normal distributions as Likelihood Function.
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @param burn Number of burn-in.
#' @return List of model coefficients and acceptance rate.
#' @export
#'
bqrNM <- function(Xr, Yr, p, nsim, initCoef, weight, mu, sigma, burn = 5000L) {
    .Call('_bqrDPM_bqrNM', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, weight, mu, sigma, burn)
}

#' BQR with based on t Distribution
#'
#' Bayesian quantile regression using the t-distribution with Degree of Freedom 3 as Likelihood Function.
#'
#' @param Xr Matrix of covariate.
#' @param Yr Vector of response.
#' @param p Quantile of interest.
#' @param nsim Number of simulation.
#' @param initCoef Initial value (vector) of the model coefficients.
#' @return List of model parameters including the coefficients.
#' @export
#'
bqrT3 <- function(Xr, Yr, p, nsim, initCoef, burn = 5000L) {
    .Call('_bqrDPM_bqrT3', PACKAGE = 'bqrDPM', Xr, Yr, p, nsim, initCoef, burn)
}

#' The Check Loss Function
#'
#' Check loss function for frequentist quantile regression.
#'
#' @param y Vector of observed response.
#' @param yHat Vector of fitted response.
#' @param tau Quantile of interest.
#' @return check loss between fitted and observed responses.
#' @export
#'
checkLoss <- function(y, yHat, tau) {
    .Call('_bqrDPM_checkLoss', PACKAGE = 'bqrDPM', y, yHat, tau)
}

#' Sample Quantile Function
#'
#' Compute the specified sample quantile of a given sample.
#'
#' @param array Vector of sample points.
#' @param p Quantile of interest.
#' @return the specified sample quantile of the given sample.
#' @export
#'
sampleQuantile <- function(array, p) {
    .Call('_bqrDPM_sampleQuantile', PACKAGE = 'bqrDPM', array, p)
}

